import Head from 'next/head'
import Image from 'next/image'
import {useState, useEffect} from "react";
import Header from '../components/Header';

export default function Home({windowWidth, windowHeight}) {

    


  return (
    <>
    
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;400;800&display=swap" rel="stylesheet"/>
      </Head>
     
      <Header windowWidth={windowWidth} windowHeight={windowHeight} />
    </>
  )
}
