import Head from 'next/head'
import Image from 'next/image'
import {useState, useEffect} from "react";
import Header from '../components/Header';
import Navigation from '../components/Navigation';
export default function Home() {

    const[navAnimation,setNavAnimation] = useState(true)

	// Get window width and height
	const [size, setSize] = useState({
        // windowWidth: window.innerWidth,
		// windowHeight: window.innerHeight
    })

  

	const updateSize = () => {
		setSize({
			windowWidth: window.innerWidth,
			windowHeight: window.innerHeight
		})
	}

 
	useEffect(() => {
        setSize({
			windowWidth: window.innerWidth,
			windowHeight: window.innerHeight
		})
		window.onresize = updateSize
	}, [])

    console.log(size)

  return (
    <>
    
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;400;800&display=swap" rel="stylesheet"/>
       
      </Head>
     
      <Navigation navAnimation={navAnimation} setNavAnimation={setNavAnimation} windowWidth={size.windowWidth} windowHeight={size.windowHeight}/>	
      <Header windowWidth={size.windowWidth} windowHeight={size.windowHeight} />
    </>
  )
}
